[package]
name = "oaktree"
version = "0.1.0"
edition = "2021"


[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui_extras = {version = "0.28.1", features = ["default", "image"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"



