[package]
name = "wx"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
chrono = "0.4"
chrono-tz = "0.6"
textplots = "0.8"
rgb = "0.8.50"
