[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["macbethc-byui <macbethc@byui.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.7"